---
# Install retrace-server packages
- include: install.yml
  tags: [rs, packages]

# Configure retrace-server
- include: config.yml
  tags: [rs, config]

# Check functionality of the retrace-server
- include: check.yml
  when: rs_check_health
  tags: [rs, check]
