---
- name: check if faf installed
  yum: list=faf
  register: is_installed

- fail: msg="faf is not installed!"
  when: '"installed" not in "{{ is_installed.results }}"'

- name: add user retrace to faf db
  postgresql_user: db=faf
                   name=retrace
                   priv=ALL
                   role_attr_flags=SUPERUSER
                   state=present
  become: yes
  become_user: postgres

- name: add retrace to group faf
  user: name=retrace groups=retrace,faf append=yes present=yes

- name: check for hardlink dir
  stat: path={{ rs_faf_link_dir }}
  register: rsdir

- name: make dir for hardlinks
  file: path={{ rs_faf_link_dir }} state=directory owner=retrace group=retrace
  when: rsdir.stat.exists == False

- name: restart machine after usermod
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0

- name: wait for the machine to come alive
  local_action: wait_for host="{{ ansible_ssh_host | default(inventory_hostname) }}"
                         state=started port=22 delay=30 timeout=300 connect_timeout=15
